# -*- coding: utf-8 -*-
"""train-gpt-neo-125.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LKklBq1DZ4hNdJfCWES2oKf0BHxO_XXL
"""

pip install happytransformer

from happytransformer import HappyGeneration
from happytransformer import GENSettings

happy_gen = HappyGeneration("GPT-NEO", "EleutherAI/gpt-neo-125M")
top_k_sampling_settings = GENSettings(do_sample=True, early_stopping=False, top_k=50, temperature=0.7)
result = happy_gen.generate_text("School is really ", args=top_k_sampling_settings)
print(result.text)

from happytransformer import GENTrainArgs
args = GENTrainArgs(num_train_epochs=3)
happy_gen.train("sample.txt", args=args)